### ISSUE TITLE
Astroprint tab doesn't follow CSS for the rest of Octoprint

### ISSUE THREAD

**Issue by BenWoodford** [AstroPrint/OctoPrint-AstroPrint#10]
This is mostly an issue if you have a dark theme installed. Headings, pagination, the main bar at the top of the tab should all be following the existing colours wherever possible to avoid mismatches when themes are used.

**Comment by CoDanny** [comment]
@BenWoodford Could you give more info regarding how to follow themes? Is there documentation?

**Comment by CoDanny** [comment]
Closing as there has been no follow up

**Comment by BenWoodford** [comment]
Sorry, totally forgot about this. There's no CSS guide, but it's the Themeify plugin in use. Everything else follows the correct colours but Astroprint doesn't. See below

![image](https://user-images.githubusercontent.com/503263/34767189-671d66dc-f5ef-11e7-8992-29ccf5287e25.png)

**Comment by CoDanny** [comment]
@BenWoodford Yes, we saw that. Note that the whole tab is our UI and we were able to match the style in everything except that header... At the moment I don't know how to get that container to "behave".
