### ISSUE TITLE
#101 brakes GCode Viewer css

### ISSUE THREAD

**Issue by BarakRL** [AstroPrint/OctoPrint-AstroPrint#102]
PR #101 messed up the CSS for parts of the UI unrelated to astro print, mainly the GCode viewer sliders.
![Capture](https://user-images.githubusercontent.com/4962645/103358665-d86a0300-4abe-11eb-95e4-da20dd697e60.PNG)

**Comment by CoDanny** [comment]
Thanks we will look into this.

**Comment by abbrowna** [comment]
Also misplaces sliders added as custom controls to the top left of the interface.

**Comment by Pka78** [comment]
> 
> 
> Also misplaces sliders added as custom controls to the top left of the interface.

I also have same issue, Astroprint messes up GCode viewer and also another plugin: Filament Manager.

**Comment by BarakRL** [comment]
almost 5 month and no fix?

**Comment by CoDanny** [comment]
Fixed with https://github.com/AstroPrint/OctoPrint-AstroPrint/pull/107
