### ISSUE TITLE
Can't control my printer

### ISSUE THREAD

**Issue by leobel96** [AstroPrint/OctoPrint-AstroPrint#12]
Everything works in astroprint, except the "control" tab of my printer: when I try accessing it a message appear saying I must be in the same network of my printer to control it also if I try accessing in the same network

**Comment by CoDanny** [comment]
Is this on the mobile app? If so, the app needs to be updated in order to control the OctoPi Box on local network. The next release will have it.

**Comment by leobel96** [comment]
Yes, thank you!!

**Comment by CoDanny** [comment]
I'll close this now. It's known and being addressed by the mobile app.
