### ISSUE TITLE
Administrator Access?

### ISSUE THREAD

**Issue by 3Dude10** [AstroPrint/OctoPrint-AstroPrint#16]
Trying to get the AstroPrint Plug-in to work but I am confused. It says “only accounts with administrator access can interact with the AstroPrint Plugin.” Anybody know what I did wrong and a way to get it working?

**Comment by CoDanny** [comment]
You need to have admin rights in your OctoPrint account to enable this plugin

**Comment by 3Dude10** [comment]
Can I get these rights, is it just in the settings somewhere? I am fairly new to OctoPrint, sorry if this is a dumb question.

**Comment by CoDanny** [comment]
If the box is yours, you should log into OctoPrint with the username that you used when you first setup the box.

**Comment by 3Dude10** [comment]
Just want to make it clear, this is the Raspberry Pi 3 running Octoprint not an AstroBox. I am logged in on OctoPrint But I cant use the AstroPrint because it says the message above.

**Comment by 3Dude10** [comment]
[https://plus.google.com/102577967477565381385/posts/LpC2iX4HNPn](url) Here is the link to my orginal question on google communities.  It has a picture of my screen too.

**Comment by CoDanny** [comment]
@3Dude10 I understand. My answer was related to your octoprint user, not the astroprint one.

**Comment by 3Dude10** [comment]
Sorry, I misunderstood you. I’ll check it right now.

**Comment by 3Dude10** [comment]
It is working now, thanks for all your help and staying with me.

**Comment by CoDanny** [comment]
No worries. Glad it's working :)

**Comment by GingerSneak** [comment]
This issue appears for me as well. I have only one user in my OctoPrint install. I've verified that my user has admin rights in the YAML users file. Can this be reopened?

**Comment by CoDanny** [comment]
@GingerSneak We're going to investigate. Note that there we have over 1000 users using the plugin successfully. There has to be something in your (and a few others) setup. Can you think of anything that might be different? What platform are you on?

**Comment by GingerSneak** [comment]
@CoDanny, details below:

OctoPrint version: 1.3.4
Plugin version: 1.0.1
OctoPi version: 0.14.0
Hardware: Raspberry Pi Zero W

**Comment by ihateu3** [comment]
Same issue here as well...

Was working fine forever, maybe it was the last octoprint update?

**Comment by CoDanny** [comment]
@ihateu3 Which Octoprint update, what version are you running and which version was working?

**Comment by GingerSneak** [comment]
@CoDanny, is there a log file I can look at or debugging that can be enabled to give more information?

**Comment by ihateu3** [comment]
I am not really sure which version that I was on before, but I only have had octoprint for around a month, so it was current when I built it, I am currently on 1.3.6

As far as any logs, I didn't really find anything of value, but then again I do not know really what I am looking for.  I attached a log for you to see.
[octoprint.log.2018-01-07.txt](https://github.com/AstroPrint/OctoPrint-AstroPrint/files/1624653/octoprint.log.2018-01-07.txt)

**Comment by CoDanny** [comment]
@GingerSneak In the logs directory there should be a log specific to the plugin, but it might not give any information since you can't even connect it due to the non-admin account. You can also look for javascript errors in your browser's web console.

@ihateu3 Your logs actually shows some exceptions that our plugin is putting out. It's helpful. you do have the plugin connected, correct?

**Comment by Alfonsopl** [comment]
In the last commit that was made to adapt the plugin to support browsers in "strict mode" a variable lost the scope and was not able to recognize the user's login.
In the next version will be fixed, meanwhile you can login in Octoprint with "remember me" selected and reload the page to access the Astroprint tab

**Comment by GingerSneak** [comment]
Just tried, no luck on the 'Remember Me' checkbox, it still responds the same.

**Comment by PDunham113** [comment]
@GingerSneak I had the same issue this morning, but it dissapeared after following Alfonsolpl's advice. I know it's a silly question, but did you refresh the page after logging in with the 'Remember Me' checkbox?

The Astroprint plugin DID NOT work when I re-logged in. It only started working after I refreshed the page.

**Comment by GingerSneak** [comment]
@PDunham113, just retried with a different machine and browser. Still no joy. :-(.
I think I'm going to try to roll back a few revisions and see if that helps.

**Comment by GingerSneak** [comment]
Rolled back to 1.0.0, resolved the issue. When 1.0.2 is released, I'll be happy to install and test.

On a side note, thanks to @CoDanny and @Alfonsopl for making/contributing to this plugin, and for your responsiveness and diligence with this issue. Is there somewhere I can donate?

**Comment by CoDanny** [comment]
@GingerSneak Thanks for the offer to donate. You can donate here: https://www.paypal.me/3DaGoGo

**Comment by user100000** [comment]
So how do you fix it?  I only have the default account the  octoprint   instals and I am assumming  a root account that Sudo uses.

Do I have to add  yet another  account?

**Comment by nicksears** [comment]
have you tried refreshing the page? That's what did it for me.
