### ISSUE TITLE
Plugin keeps forgetting my key

### ISSUE THREAD

**Issue by BenWoodford** [AstroPrint/OctoPrint-AstroPrint#19]
Or something like that. I regularly find that Astroprint no longer knows about my printer, and I have to re-enter my Astroprint key.

Any ideas?

**Comment by CoDanny** [comment]
It's likely that the access token is being deleted. How often does this happen? Can you give more details?

Do you log out of your OctoPi? Does it just happen by itself?

**Comment by BenWoodford** [comment]
I'd probably say it's most common overnight. My Octoprint server is online 24/7, and isn't in a docker container or anything so it's not like it's got a config to lose.

Saying there, the config.yaml _does not_ have my API key saved in it. Could it be that?

**Comment by GitSoks** [comment]
I have the same problem my key is reseting every time I disconnect the raspberry from power (i don't know if this also happens if I shut it down normally)

**Comment by foo25amc** [comment]
This also happens to me every time I shutdown or reboot. It's a shame, because the notification and email is really useful!

**Comment by Alfonsopl** [comment]
Could you provide more information about your environment and octopi, and plugin version?

**Comment by foo25amc** [comment]
I'm using a RPi3 running OctoPrint v1.3.6, OctoPi v0.14.0, and Astroprint v1.0.2. All packages are also up to date.

**Comment by Joe-houghton** [comment]
Hi,

I know this issue is closed, but it is happening to me also. It seems to be when I do not select "Shutdown" and instead just pull the power.

Joe

**Comment by Alfonsopl** [comment]
I can not reproduce the error.
Could you provide more information about your environment and octopi, and plugin version?
Also are you logged to your octopi account after you reboot/shutdown?

**Comment by Joe-houghton** [comment]
Hi,
Sorry about the delay.
I am using Octopi 1.3.9 (although it was happening in 1.3.8 too)
I installed AstroPrint plugin via the plugin manager and it says version AstroPrint (1.1.0).
Yes I am logged into Octopi after a shutdown, using Raspberry Pi 3.

Is there any more information that I can give you?

Joe

**Comment by raffaelps** [comment]
I had the same error, every time when my Octopi shutdown, when I turn on the Octopi the plugin lost the key.

- Octopi Version 1.3.9
- AstroPrint Version 1.1.0

Thanks

**Comment by Alfonsopl** [comment]
I have try with different versions of plugin and octopi and I am still not able to reproduce this error.

I think that the error could be that the plugin is not saving data into its database, that is why it can not find your access token.

Could you check if there is any encrypted data (or even file created) on /.octoprint/data/astroprint/octoprint_astroprint.db ?

**Comment by raffaelps** [comment]
No @Alfonsopl, there isn't any encrypted data.

**Comment by jmichelsen** [comment]
I experience this issue too. I thought I had a corrupted SD card so I actually just rebuilt my octopi setup on a new card with the current version of octopi and astroprint. If the pi gets rebooted, regardless of the method (shutdown, restart, loss of power), I have to re-enter my API key.

**Comment by CoDanny** [comment]
@raffaelps  if this file ```/.octoprint/data/astroprint/octoprint_astroprint.db``` doesn't exists, that is the problem. Now we need to find out why it can't be created. Are you able to access the plugin logs and send them to us?

**Comment by FedorSosnin** [comment]
Sadly, having the same issue.

**Comment by daijoubu** [comment]
Myself as well.  I did find the settings file specified on my raspberry pi,
but can't confirm if the key was correctly stored or not.

**Comment by Selfsustained** [comment]
@CoDanny I am not finding any astroprint directories after install. Using both putty and WinSCP over ssh to rpi3.  Octoprint version: 1.3.9   Octopi version: 0.15.1  Astroprint version: 1.1.0

Edit: Immediately upon inputting my key and clicking link account button, page refreshes to astroprint asking for my permission. Upon authorizing and page refreshes back to octoprint there is an error that states that boxrouter could not connect. I am adding a small snip picture of what shows up.
![capture](https://user-images.githubusercontent.com/44002153/46688209-60a01d00-cbc2-11e8-97af-13c90fdb7931.PNG)

**Comment by ghost** [comment]
Did any one find the solution to this problem? I have fully setup the printer to run remotely including powering on/off, cam and Octopi. Now it is useless since I have to be connected to the local network to enter the key every time.

**Comment by ckohljr** [comment]
Bump - I also have this issue when I power cycle my OctoPI.  I have recently installed OctoPrint image and AstroPrint plugin within the last 2 weeks and it loses my key every time I reboot. Any Help?

**Comment by Alfonsopl** [comment]
> Bump - I also have this issue when I power cycle my OctoPI. I have recently installed OctoPrint image and AstroPrint plugin within the last 2 weeks and it loses my key every time I reboot. Any Help?

Could you report what permissions has /.octoprint/data/astroprint/octoprint_astroprint.db ? Looks like the data is not being stored on database, and that is why the plugin "loses" the key on reboot. Some of the users has already reported that this file is empty.

**Comment by ckohljr** [comment]
Thanks for the quick response, here are the permissions on the db:

pi@ender3octopi:~/.octoprint/data/astroprint $ ls -l
total 16
-rw-r--r-- 1 pi pi 16384 Jan 16 05:00 octoprint_astroprint.db
pi@ender3octopi:~/.octoprint/data/astroprint $

I don't know why GitHub is using strikeout on the command but it is:
-rw-r--r--

**Comment by flyingelephant19** [comment]
i get the same issue. well everytime i shutdown the PI and restart, the creditials are gone and have to re enter and on one of my PI's i am running the latest 0.16 octopi.

**Comment by markarsenich** [comment]
I'm also having the same issue and I have NO IDEA how to fix it... every time I reboot I loose the access key. Upon print completion my Octroprint sends a shutdown request via IFTTT to my wifi plug and it turns everything off thats plugged into my surge bar. when i turn everything back on theres no key, i have to log into astroprint.com, get the key, copy it over. has essentially made Astroprint (which i love) useless to me. PLEASE HELP!

**Comment by CoDanny** [comment]
@markarsenich Does the same happen if you don't turn everything off that way and instead simply reboot the box via the octoprint options?

**Comment by markarsenich** [comment]
FIXED! All I did was uninstall reboot, re-install reboot, now it works, cut power multiple times, stays logged in.

**Comment by flyingelephant19** [comment]
mark, i cant say the same for me :(

**Comment by flyingelephant19** [comment]
are there any logs that can be given ?

**Comment by markarsenich** [comment]
well spoke too soon, not fixed, logging out on power off/on again... about to uninstall this plugin

**Comment by CoDanny** [comment]
@markarsenich Does the same happen if you don't turn everything off that way and instead simply reboot the box via the octoprint options?

Also are there any other plugins you installed between the time it was working and when it stopped working? Our current assumption is that another plugin is causing this behavior when installed together with ours. We just don't know which just yet.

**Comment by drzejkopf** [comment]
I experience very same problem with plugin, and it's really irritating. If it's really related to other plugins then maybe it's good idea for everyone experiencing it to post which (non-bundled) plugins they have installed, then it will be easier to tell which plugin/plugins may possibly cause problems, I will start:
-Action Commands (0.1)
-AstroPrint (1.2.0)
-DeleteAfterPrint Plugin (1.2.0)
-Exclude Region (0.1.3)
-Fan Speed Control (0.2.1)
-Filament Manager (0.5.3)
-FileManager (0.1.3)
-Firmware Updater (1.1.0)
-GcodeEditor (0.2.6)
-ipOnConnect (0.2.1)
-M73-Progress-Plugin (0.1.0)
-OctoKlipper (0.2.5)
-PrintTimeGenius Plugin (1.3)
-Tempsgraph Plugin (0.3.3)
-Themeify (1.2.0)

**Comment by CoDanny** [comment]
Is it possible to disable/delete the "DeleteAfterPrint Plugin" to see if that fixes the issue?

**Comment by Steveps3** [comment]
I recently (2 months or so) changed my printer setup so that my pi is powered directly from the printer. Since i did this I am also losing my Astroprint API setting. This only happens once a week or so. Which is quite odd. Obviously the API is being written to the memory card but something is occasionally deleting it. I am on the verge of ditching Astroprint because is becoming so annoying.

**Comment by CoDanny** [comment]
@Steveps3 since it was working before your change, why not looking at what changed that makes the plugin behave like this? Then we can maybe fix it.

**Comment by Steveps3** [comment]
I thought that I'd explained what had changed? My raspberry pi is now powered from the printer. This means that when the printer turns off, so does the pi. There is something in the octoprint software that is just losing the astroprint API setting. This only happens maybe once a week so the problem is not as described above. The file that stores the API key is there most of the time.

**Comment by CoDanny** [comment]
Ok. So the problem here is that the PI is being cut off without a graceful OctoPrint shutdown? I don't think there's much we can do about this. The system will be caught off guard by a sudden loss of power. In some cases the file with the data might not have been written to the system. This is the reason OctoPrint has a software shutdown/halt that should be used before cutting power.

**Comment by Steveps3** [comment]
I have tried using the shutdown and it does the same thing. Which is why I don't bother with it any longer. Also why would cutting the power delete the API setting. The API setting can be there for 4-5 power cycles and then it is gone. It just doesn't make sense. Maybe I could change the permissions on the file so that it cannot be written to once it has the API setting.

**Comment by CoDanny** [comment]
The same file is used to store other settings so it would depend of what the machine is doing at the time the power is cut. We'll keep looking into it. I thought this could've bee a solid lead but it appears not. We are completely UNABLE to reproduce this behavior and I would say it happens to less than 5% of the plugin users.

It's quite frustrating for us too as the first step to fix a problem is to be able to reproduce it in a controlled environment. Anyway thanks for your patience, we will eventually find this 🐛 and fix it.

**Comment by Steveps3** [comment]
I am a software engineer so I totally understand your frustration. Being able to recreate a problem is half the battle. I have just spent the last 2 days trying to recreate something. I asked someone about it and they were able to show me the correct settings to recreate it. So frustrating :)

Maybe I will try the uninstall / reinstall method but I do have 2 printers and they both exhibit the same behaviour. I have considered going back to having the pi powered all the time but that has the complication that when I do turn on the printer, Octoprint doesn't automatically connect to it. So i have to "connect" manually. So I have a toss up between having to connect manually every time or having to reentered the API key once a week.

**Comment by CoDanny** [comment]
There's a new version (1.2.1) that adds some logging and fixes other things. Please update to it and when this error happens again, reach out so we can take a look at your log.

**Comment by Steveps3** [comment]
Well it's done it again. So if you want to tell me where to find the log ans where to send it then I'll be glad to do so.

**Comment by CoDanny** [comment]
You can access and download files here. If you don't mind [open a ticket with us](https://astroprint.zendesk.com/hc/en-us/requests/new) to share logs. We will post back here when something relevant is found.

![capture](https://user-images.githubusercontent.com/542760/55388490-b3d0a800-5533-11e9-9c6b-84f922258ab0.gif)

**Comment by zigzaggin** [comment]
I had this issue as well. 

I was able to correct the issue by adjusting the permissions on the octoprint_astroprint.db file located in ~/.octoprint/data/astroprint/

I pushed the settings out to 777 because frankly its a closed box and I don't really care... but lower may also work.

Prior to the changed permissions, pulling the power cord caused the plugin to lose my API key, and now I am retaining it after multiple hard power resets.

Command to run if you're newer to pi, but please understand chmoding something to 777 isn't great practice, and starting lower and working up may be worthwhile.

sudo chmod 777 ~/.octoprint/data/astroprint/octoprint_astroprint.db

**Comment by CoDanny** [comment]
Could you try installing the new version of the plugin (1.3.0) and see if this problem goes away. You might have to enter the credentials one more time after installation.

**Comment by Steveps3** [comment]
Ok, I’ll try that. 
Thanks

**Comment by Steveps3** [comment]
It failed after just a day. Same as before, astroprint cannot find the printer.

**Comment by CoDanny** [comment]
@Steveps3 I'm a bit confused but this sentence "astroprint cannot find the printer". Do you mean it disconnects from the cloud? Does it ask you for the key again when you go to your OctoPrint interface?

what do you have in the ```/.octoprint/data/astroprint``` directory?

**Comment by Steveps3** [comment]
No, it simply says "no remote connections"

**Comment by CoDanny** [comment]
Ok, what does the OctoPrint interface say? and also if you could look in the directory I mentioned, that would help

**Comment by Steveps3** [comment]
I am not at home right now. Which is why I need astroprint to be working. I will check tonight.

**Comment by Steveps3** [comment]
That directory doesn't exist. Which might explain a few things.

**Comment by sloth711** [comment]
hello

i have the same problem with the lastest version on octoprint and astroprint

after i discconnect my print 1h of plug on app android says " you need be logged"

to solve i need to re-install every time new key

please solve that 

thank you

**Comment by rchoughton** [comment]
Has anyone figured out how to solve this problem?

**Comment by CoDanny** [comment]
@rchoughton Our best guess right now is that in some installations filesystem permissions are preventing our files from being written and there not able to persist the key values.

**Comment by rchoughton** [comment]
Are these permissions that I can go in and change? Will they will stick making the system remember the key?

**Comment by CoDanny** [comment]
You can change the permissions of the directory: ```/home/pi/.octoprint/data/astroprint```

@Steveps3, the path I gave you before was wrong. Can you check this new one?

**Comment by Steveps3** [comment]
I have two files in that directory
print_files.yaml 
user.yaml

**Comment by Steveps3** [comment]
These are the permissions that I have
![image](https://user-images.githubusercontent.com/6318429/57966755-2663de80-794e-11e9-9a9c-c6d0c0283bb0.png)

**Comment by CoDanny** [comment]
Thanks @Steveps3, What about the permissions of the files themselves? Also does the octoprint daemon run under the 'pi' user?

**Comment by Steveps3** [comment]
The file permissions are
![image](https://user-images.githubusercontent.com/6318429/57968035-4222b100-795d-11e9-95ba-c5bc6dd73d84.png)

Yes, everything is running under the pi user.

**Comment by CoDanny** [comment]
can you give write permissions to all and reboot just to test if that helps with your problem. You might have to enter the key one time after reboot and then it should stick

**Comment by Steveps3** [comment]
Done. I will have to see how it gets on.

**Comment by sloth711** [comment]
Hello... The problem it's solve?

**Comment by Steveps3** [comment]
It is a bit optimistic to say that.

**Comment by Steveps3** [comment]
Failed again.

**Comment by rchoughton** [comment]
Same for me. It seemed to work for a few days and then it started loosing the key yesterday again.

**Comment by CoDanny** [comment]
We have a new clue about this problem. Some people that see this happen in their installation had cloned their sd card from another working octopi. This creates a problem by which two boxes are registering in the AstroPrint network with the same box id, which makes one of them invalid and could be causing this.

If this was the case, could you simply remove the ```box-id``` file referenced here. It should be in the same directory as your ```config.yaml```: https://github.com/AstroPrint/OctoPrint-AstroPrint/blob/1c9b385daaaf57767a927015aacf21b0e3b8daff/octoprint_astroprint/boxrouter/__init__.py#L187 

then restart. This might fix the issue. 

Let us know by giving this comment a thumbs up if it does or a thumbs down if it doesn't

Reference: https://forum.astroprint.com/t/can-t-set-up-the-astroprint-plugin-on-my-second-octopi/4635/3

**Comment by Steveps3** [comment]
Hi Daniel,
My SD was not cloned but I will certainly give that a try. 
ThanksSteve

Sent from Yahoo Mail for iPhone

**Comment by seltix5** [comment]
I have the same problem =/

**Comment by CoDanny** [comment]
@seltix5 Did you create your octopi by cloning another box?

**Comment by seltix5** [comment]
No, clean install and installed plugin

**Comment by CoDanny** [comment]
New Release 1.3(2) with another attempt to fix this. Let me know if anybody in this thread can see improvements regarding the problem being discussed.

**Comment by cable1996** [comment]
Yeah, I updated with the release, and now I'm having the issue when it didn't happen before.

**Comment by Steveps3** [comment]
Welcome to the club.

**Comment by Steveps3** [comment]
I assume the new method is to have the connection to AstroPrint reconnect every 5 seconds? On my iPad I am constantly being spammed by AstroPrint connection toast when I view the octoprint interface. So now I have to disconnect from AstroPrint just so that I can use octoprint.

**Comment by CoDanny** [comment]
Absolutely not @Steveps3, your box certainly has a problem connecting and keep the connection. We do try to reconnect when the connection is lost but it shouldn't be every 5 secs. This is likely the root problem. Please open a ticket with us to see what might be going.

**Comment by rchoughton** [comment]
I have been using for a few days and this morning the key was lost and I have to redo it.

**Comment by seltix5** [comment]
I can confirm too, the problem is still there. Today I try to use it and the key was lost. I can't say when it append but it was after last update.

**Comment by CoDanny** [comment]
The key can be lost for many other reasons including expiration of credentials after not using it for a long time. This problem was about they key being forgotten repeatedly in a short amount of time. After consulting with a few affected users, this particular problem (there might be others) seems to have been solved. Two things were causing it:

1) A bug in our software by which a rejection of connection by our servers would log the user out. This sometimes meant that poor connectivity or misconfigured boxes (see second reason below) could wrongly log you our and ask you to log in again.

2) Users using an OctoPi devices which was made off a clone of another one were the plugin was active created a situation where two boxes were being logged into our system as one. When a box logs into our system with the same Box Id as another, the previous one is kicked out, this caused reason number 1 above happened.

This issues has now grown quite large and is confusing people that for other reasons loose their credentials on occasion to add comments here. I'm going to close and lock this issue now.

If you experience loss of credentials again, please reopen another ticket and explain how often this happens, look to see if you have more than one OctoPi connected to your account and whether the second one was a clone of the first and provide this info in the ticket.
