### ISSUE TITLE
Causes crashes in OctoPrint's login when disabled

### ISSUE THREAD

**Issue by foosel** [AstroPrint/OctoPrint-AstroPrint#26]
I just had a user report an odd issue in foosel/OctoPrint#2442. They have the Astroprint plugin disabled, and that makes them not able to login anymore.

A closer look at OctoPrint's plugin subsystem reveals that contrary to what I so far assumed, plugins are still loaded even when disabled. Which means that in your case the plugin's implementation will be initialized, and in its constructor functions will be attached to Flask Login's loggedIn and loggedOut signals that try to send messages to the frontend via `self._plugin_manager` - however, if your plugin is disabled, your plugin won't be fully initialized, `self._plugin_manager` hence not injected and that means things crash inside Flask Login when trying to call your signal handler and the login fails with an HTTP 500.

I'll have to do something about this on OctoPrint's side, however I strongly suggest to not attach any stuff to the system as long as the plugin is not fully initialized (read: the `initialized` method on it is called). 

Could you fix this on your end? As I said, I'll also look into finding a good fix on mine. If push comes to shove, disabled plugins will simply get the same treatment that blacklisted ones get, meaning some metadata will be missing in the plugin list but no code will be executed at all, preventing such issues in the future.

**Comment by CoDanny** [comment]
For sure @foosel, we have a new release coming up to improve support of the plugin in our mobile app and we will include this as well
