### ISSUE TITLE
Printer name with multiple printers

### ISSUE THREAD

**Issue by TeeJS** [AstroPrint/OctoPrint-AstroPrint#32]
I have multiple OctoPrint-AstroPrint devices linked to my account.  It's difficult to use the monitor or print queue function of Astroprint, as all the printers are named "octopi"  could it use the Title from the appearance section of OctoPrint or give you an option to set the name in AstroPrint?
![capture](https://user-images.githubusercontent.com/4136437/37681968-cf9a71f2-2c4d-11e8-8f63-897404583911.JPG)

**Comment by CoDanny** [comment]
@TeeJS We currently use your hostname. Which is given to you octopi at the system level, you can change it on the OS level. However we will look to see if we can facilitate this from our plugin.

**Comment by TeeJS** [comment]
Knowing it takes it from the hostname is great, thanks!
