### ISSUE TITLE
installing Astroprint via pip installs the wrong version of pillow

### ISSUE THREAD

**Issue by cnschu** [AstroPrint/OctoPrint-AstroPrint#34]
**expected behavior:**
installing AstroPrint via pip uses the existing pillow version if > 3.1.0

**observed behavior:**
installing Astroprint via pip with an pillow version of 5.0.0 installed deinstalls pillow and installs pillow version 3.1.0

**Comment by CoDanny** [comment]
Thanks for this, we will change the dependency definition

**Comment by CoDanny** [comment]
We have changed the dependencies. Try installing the plugin that requires the 5.0 and then try the astroprint plugin again.

**Comment by cnschu** [comment]
thanks
