### ISSUE TITLE
Robo print profiles

### ISSUE THREAD

**Issue by AllenMcAfee** [AstroPrint/OctoPrint-AstroPrint#39]
@CoDanny I just tested the latest prerelease you posted earlier today.  Things are testing well, but i do want to get our print profiles down.  Can you take a look at https://github.com/Robo3D/Slicing-Profiles/tree/master for our profile for all versions of cura?  I'm noticing the PLA is printing at 215C on the C2, and we tend to print closer to 190C.

**Comment by CoDanny** [comment]
@AllenMcAfee, I can get you setup with access to the Robo settings so you (or somebody at Robo) can do that at any time. I'll contact you directly to set it up
