### ISSUE TITLE
Notifications no longer working after installing v1.0.9

### ISSUE THREAD

**Issue by vbasrar** [AstroPrint/OctoPrint-AstroPrint#41]
Since installing the 1.0.9 updated version on to my 3 octoprint servers, the notifications of prints completing has stopped working. It no longer sends emails or mobile notifications. I have checked and re-entered the API key and it appears all connected fine. I can view the status of all the printers/jobs, just no notification at the end.

**Comment by CoDanny** [comment]
Thanks for the report. Fix coming up shortly

**Comment by vbasrar** [comment]
I can confirm it is all working correctly again following installation of 1.0.10. Many thanks for the very quick response.
