### ISSUE TITLE
Astroprint requires pillow <= 3.1.0 but other apps <= 5.0.0

### ISSUE THREAD

**Issue by w4www** [AstroPrint/OctoPrint-AstroPrint#43]
When will the dependency on pillow <= 3.1.0 be updated to allow for 5.x?

astroprint 1.0.10 has requirement Pillow<=3.1.0, but you'll have pillow 5.0.0 which is incompatible.

**Comment by CoDanny** [comment]
Thanks for reporting, we're looking the compatibility and will adjust
