### ISSUE TITLE
OctoPrint Change Box Name Hangs on Save

### ISSUE THREAD

**Issue by dataman** [AstroPrint/OctoPrint-AstroPrint#48]
Astoprint Plugin for Octoprint hangs when changing box name.
When clicking save, spinner spins and server returns.
Close Dialog.
Reboot.
Return to astroprint name is changed.

**Comment by Alfonsopl** [comment]
It seems that with the new version of octoprint there are no incoming messages from the web socket.
You do not need to restart, you are currently changing the name you can see on the monitor or tab.
It will be fixed soon, thanks for the report.
