### ISSUE TITLE
Installing Plugin 

### ISSUE THREAD

**Issue by drkbalamurugan** [AstroPrint/OctoPrint-AstroPrint#56]
Installing plugin "AstroPrint Cloud" from https://github.com/AstroPrint/OctoPrint-AstroPrint/archive/master.zip...
c:\octoprint\venv\scripts\python.exe -m pip install https://github.com/AstroPrint/OctoPrint-AstroPrint/archive/master.zip --no-cache-dir
Collecting https://github.com/AstroPrint/OctoPrint-AstroPrint/archive/master.zip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Downloading https://github.com/AstroPrint/OctoPrint-AstroPrint/archive/master.zip
Requirement already satisfied: OctoPrint in c:\octoprint\venv\lib\site-packages (from AstroPrint==1.2.0) (1.3.10)
Collecting ws4py==0.3.4 (from AstroPrint==1.2.0)
Downloading https://files.pythonhosted.org/packages/aa/60/5d135c8161a2a67d7c227d57bb599fad967d818dbcdca08daa2d60eb87b9/ws4py-0.3.4.tar.gz
Collecting requests_toolbelt==0.8.0 (from AstroPrint==1.2.0)
Downloading https://files.pythonhosted.org/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl (54kB)
Collecting Pillow (from AstroPrint==1.2.0)
Downloading https://files.pythonhosted.org/packages/a5/66/433aa868409dcacdd431e2b73ea0b21d66f0ed3911a3c25305eec1d27900/Pillow-5.4.1-cp27-cp27m-win32.whl (1.6MB)
Requirement already satisfied: Flask-Principal<0.4,>=0.3.5 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.3.5)
Requirement already satisfied: markdown<2.7,>=2.6.9 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (2.6.11)
Requirement already satisfied: pylru<1.1,>=1.0.9 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (1.0.9)
Requirement already satisfied: frozendict<1.3,>=1.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (1.2)
Requirement already satisfied: future<0.16,>=0.15.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.15.2)
Requirement already satisfied: flask<0.11,>=0.10.1 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.10.1)
Requirement already satisfied: feedparser<5.3,>=5.2.1 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (5.2.1)
Requirement already satisfied: awesome-slugify<1.7,>=1.6.5 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (1.6.5)
Requirement already satisfied: watchdog<0.9,>=0.8.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.8.3)
Requirement already satisfied: Flask-Assets<0.11,>=0.10 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.10)
Requirement already satisfied: requests<3,>=2.18.4 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (2.21.0)
Requirement already satisfied: websocket-client<0.41,>=0.40.0 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.40.0)
Requirement already satisfied: Click<6.3,>=6.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (6.2)
Requirement already satisfied: Flask-Babel<0.10,>=0.9 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.9)
Requirement already satisfied: psutil<5.5,>=5.4.6 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (5.4.8)
Requirement already satisfied: Jinja2<2.9,>=2.8.1 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (2.8.1)
Requirement already satisfied: emoji<0.5,>=0.4.5 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.4.5)
Requirement already satisfied: pyserial<3.5,>=3.4 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (3.4)
Requirement already satisfied: regex!=2018.11.6 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (2019.1.23)
Requirement already satisfied: Flask-Login<0.3,>=0.2.11 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.2.11)
Requirement already satisfied: semantic-version<2.5,>=2.4.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (2.4.2)
Requirement already satisfied: wrapt<1.11,>=1.10.11 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (1.10.11)
Requirement already satisfied: monotonic<1.4,>=1.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (1.3)
Requirement already satisfied: PyYAML<3.11,>=3.10 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (3.10)
Requirement already satisfied: pkginfo<1.5,>=1.4.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (1.4.2)
Requirement already satisfied: netifaces<0.11,>=0.10.6 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.10.9)
Requirement already satisfied: chainmap<1.1,>=1.0.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (1.0.2)
Requirement already satisfied: python-dateutil<2.7,>=2.6.1 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (2.6.1)
Requirement already satisfied: netaddr<0.8,>=0.7.19 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.7.19)
Requirement already satisfied: futures<3.2,>=3.1.1 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (3.1.1)
Requirement already satisfied: rsa<3.3,>=3.2.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (3.2.3)
Requirement already satisfied: sarge==0.1.5post0 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.1.5.post0)
Requirement already satisfied: werkzeug<0.9,>=0.8.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (0.8.3)
Requirement already satisfied: tornado==4.5.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (4.5.3)
Requirement already satisfied: scandir<1.4,>=1.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->AstroPrint==1.2.0) (1.3)
Requirement already satisfied: blinker in c:\octoprint\venv\lib\site-packages (from Flask-Principal<0.4,>=0.3.5->OctoPrint->AstroPrint==1.2.0) (1.4)
Requirement already satisfied: itsdangerous>=0.21 in c:\octoprint\venv\lib\site-packages (from flask<0.11,>=0.10.1->OctoPrint->AstroPrint==1.2.0) (1.1.0)
Requirement already satisfied: Unidecode<0.05,>=0.04.14 in c:\octoprint\venv\lib\site-packages (from awesome-slugify<1.7,>=1.6.5->OctoPrint->AstroPrint==1.2.0) (0.4.21)
Requirement already satisfied: pathtools>=0.1.1 in c:\octoprint\venv\lib\site-packages (from watchdog<0.9,>=0.8.3->OctoPrint->AstroPrint==1.2.0) (0.1.2)
Requirement already satisfied: argh>=0.24.1 in c:\octoprint\venv\lib\site-packages (from watchdog<0.9,>=0.8.3->OctoPrint->AstroPrint==1.2.0) (0.26.2)
Requirement already satisfied: webassets>=0.10 in c:\octoprint\venv\lib\site-packages (from Flask-Assets<0.11,>=0.10->OctoPrint->AstroPrint==1.2.0) (0.12.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\octoprint\venv\lib\site-packages (from requests<3,>=2.18.4->OctoPrint->AstroPrint==1.2.0) (2018.11.29)
Requirement already satisfied: idna<2.9,>=2.5 in c:\octoprint\venv\lib\site-packages (from requests<3,>=2.18.4->OctoPrint->AstroPrint==1.2.0) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\octoprint\venv\lib\site-packages (from requests<3,>=2.18.4->OctoPrint->AstroPrint==1.2.0) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\octoprint\venv\lib\site-packages (from requests<3,>=2.18.4->OctoPrint->AstroPrint==1.2.0) (1.24.1)
Requirement already satisfied: six in c:\octoprint\venv\lib\site-packages (from websocket-client<0.41,>=0.40.0->OctoPrint->AstroPrint==1.2.0) (1.12.0)
Requirement already satisfied: speaklater>=1.2 in c:\octoprint\venv\lib\site-packages (from Flask-Babel<0.10,>=0.9->OctoPrint->AstroPrint==1.2.0) (1.3)
Requirement already satisfied: Babel>=1.0 in c:\octoprint\venv\lib\site-packages (from Flask-Babel<0.10,>=0.9->OctoPrint->AstroPrint==1.2.0) (2.6.0)
Requirement already satisfied: MarkupSafe in c:\octoprint\venv\lib\site-packages (from Jinja2<2.9,>=2.8.1->OctoPrint->AstroPrint==1.2.0) (1.1.0)
Requirement already satisfied: pyasn1>=0.1.3 in c:\octoprint\venv\lib\site-packages (from rsa<3.3,>=3.2.3->OctoPrint->AstroPrint==1.2.0) (0.4.5)
Requirement already satisfied: backports-abc>=0.4 in c:\octoprint\venv\lib\site-packages (from tornado==4.5.3->OctoPrint->AstroPrint==1.2.0) (0.5)
Requirement already satisfied: singledispatch in c:\octoprint\venv\lib\site-packages (from tornado==4.5.3->OctoPrint->AstroPrint==1.2.0) (3.4.0.3)
Requirement already satisfied: pytz>=0a in c:\octoprint\venv\lib\site-packages (from Babel>=1.0->Flask-Babel<0.10,>=0.9->OctoPrint->AstroPrint==1.2.0) (2018.9)
Exception:
Traceback (most recent call last):
File "c:\octoprint\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 176, in main
status = self.run(options, args)
File "c:\octoprint\venv\lib\site-packages\pip\_internal\commands\install.py", line 346, in run
session=session, autobuilding=True
File "c:\octoprint\venv\lib\site-packages\pip\_internal\wheel.py", line 848, in build
assert building_is_possible
AssertionError
You are using pip version 19.0, however version 19.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by CoDanny** [comment]
It appears to be a problem with pip and not the plugin. Can you try to upgrade the pip version with:

```
python -m pip install --upgrade pip
```
