### ISSUE TITLE
Not seeing any way to link Astroprint account to Octopi

### ISSUE THREAD

**Issue by kennethpangky** [AstroPrint/OctoPrint-AstroPrint#8]
https://imgur.com/a/5ExA2

As in image, there is no way for me to enter the Access Key from Astro Cloud Settings into the Astroprint plugin. I have tried enabling CORS but no change. Or am I doing something wrong?

**Comment by CoDanny** [comment]
When you install the plugin, a new tab called “AstroPrint” is added to the OctoPrint menu ( alongside “Control”, “Terminal”, “Timelapse”, etc)

It’s there that you make the connection.

This seems to be confusing, you’re not the first one to ask. We’ll add an option in settings

**Comment by BenWoodford** [comment]
Yeah the confusion is purely down to the fact that you've got the tab on the dashboard for adding the key, but then every other setting is under settings.
