### ISSUE TITLE
Printer not getting the file from AstroPrint 

### ISSUE THREAD

**Issue by tytech038** [AstroPrint/OctoPrint-AstroPrint#84]
My printer is connected to the Astroprint cloud with octoprint. I tried to upload and slice in AstroPrint, That worked, but when i tried to send the print to the printer, It said it could not receive the file.
How do I fix this?

**Comment by tytech038** [comment]
My octoprint.log file
[octoprint.log](https://github.com/AstroPrint/OctoPrint-AstroPrint/files/4335107/octoprint.log)

**Comment by CoDanny** [comment]
The log doesn't show any relevant errors. This might be caused by network problems. In any case could you share a screenshot of the astroprint cloud's error?

**Comment by tytech038** [comment]
This is what it says on my PC
![Screen Shot 2020-03-16 at 12 13 04 PM](https://user-images.githubusercontent.com/62194272/76784961-96b3da00-6782-11ea-84d5-c0c0a7b234d3.png)
And here is what it says on my phone (with CORS on)
![IMG_1518](https://user-images.githubusercontent.com/62194272/76785038-b3501200-6782-11ea-8b5c-25dd410c70f1.PNG)

**Comment by CoDanny** [comment]
ok, weird. What's the status of the printer in the app? Not operational means that the raspberry pi is not connected to the printer. I'm assuming it is?

**Comment by tytech038** [comment]
It is,
It prints just fine from TSD or Octoprint itself.
