### ISSUE TITLE
Tab not Appearing on Octoprint side

### ISSUE THREAD

**Issue by alasharim** [AstroPrint/OctoPrint-AstroPrint#9]
Octoprint: 1.3.6
    Octopi: 0.14
  Chrome: 63.0.3239.84 (Official Build) (64-bit)
         OS: Windows 10 (64-bit)

I installed the latest AstroPrint Plugin and a Tab never Appeared so I reinstalled the plugin and the same problem persists, and yes I restarted in all of the installs/uninstalls.

![image](https://user-images.githubusercontent.com/26365097/34071106-444d742e-e282-11e7-8de9-da0024507a5a.png)

**Comment by CoDanny** [comment]
Do you see the AstroPrint plugin settings tab on settings? Does the plugin manager show the astroprint plugin installed?

**Comment by alasharim** [comment]
somehow the problem fixed its self, thanks for the great plugin 👍

**Comment by CoDanny** [comment]
Thanks!
