### ISSUE TITLE
[ Camera ] Video on mobile app seems to not apply rotation settings

### ISSUE THREAD

**Issue by CoDanny** [AstroPrint/OctoPrint-AstroPrint#97]
OctoPrint Settings 

![image](https://user-images.githubusercontent.com/542760/96633419-5e2c3e00-1319-11eb-9790-9ef3be255b72.png)

App photos

![image](https://user-images.githubusercontent.com/542760/96633449-6a180000-1319-11eb-8e5e-fc945ba7df17.png)

App Video

![image](https://user-images.githubusercontent.com/542760/96633478-72703b00-1319-11eb-8b10-c2ae40ef55ba.png)

User reports that the video shows properly within OctoPrint

**Comment by Alfonsopl** [comment]
Issue fixed by AstroPrint-Mobile new version
